### ISSUE TITLE
Anchor on the slide item doesn't work

### ISSUE THREAD

**Issue by onlinebizsoft** [tannerhodges/snap-slider#23]
If we put any URL on the slide image, clicking on the slide item doesn't go to to target URL but just scroll the slide.

**Comment by onlinebizsoft** [comment]
@tannerhodges

**Comment by tannerhodges** [comment]
@onlinebizsoft Can you share a code example or URL where you're seeing links not working within a slider?

For example, here's a basic CodePen showing that links within a Snap Slider should still work: https://codepen.io/tannerhodges/pen/dyzmExE

My first thought is there may be a separate issue (e.g., other CSS or JavaScript on the page) causing your links to not work.

**Comment by tannerhodges** [comment]
Hey @onlinebizsoft, checking in here.

❓ Were you able to solve this issue?

**Comment by onlinebizsoft** [comment]
@tannerhodges thanks for checking in, yes it worked after some updates our HTML. I guess it is not something to do with your lib.

**Comment by tannerhodges** [comment]
🙏 Awesome. Glad to hear you got it sorted out.

Thanks!
