### ISSUE TITLE
Add resistance when scrolling after the last element

### ISSUE THREAD

**Issue by andresespinosapc** [tannerhodges/snap-slider#32]
As an example, open this website on mobile: https://snipfeed.co/wateryaquarius

You can drag to the left on the first element or to the right on the last element and it has a good animation. I've seen it also uses CSS's scroll-snap, so it should be possible to replicate it in this library.

**Comment by andresespinosapc** [comment]
Sorry I was wrong, the behavior of that website already works. The problem is that there is no such edge resistance when there are no more elements to scroll (only one page of elements). Could it be possible to add edge resistance in that case?

**Comment by tannerhodges** [comment]
❓ Hey @andresespinosapc, could you share a code example where you're seeing this issue? And what device and browser you're testing with?

That will help me test and see what's going on.

I tried taking a look at https://snipfeed.co/wateryaquarius, but like you said it seems like that site's slider already animates smoothly (at least when testing on my iPhone XR with iOS 15.4.1).

https://user-images.githubusercontent.com/1619485/175201774-49f65847-328d-4e4a-a33f-eb7b85e28460.MP4

**Comment by tannerhodges** [comment]
Hey @andresespinosapc, since I haven't heard back I'm going to go ahead and close this issue.

Feel free to re-open it, though, if you still have questions I can help with.
